language: c

jobs:
  include:
    - stage: build all
      os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          packages:
            - ninja-build

    - #stage: MacOS build
      os: osx
      osx_image: xcode11.2
      compiler: gcc
      addons:
        homebrew:
          packages:
            - ninja

    - #stage: Win64 build
      os: windows
      compiler: gcc
      install:
        - choco install ninja

before_script:
  - env
  - mkdir build
  - cd build
  - cmake ${CMAKE_FLAGS} ..

script:
  - cmake --build . --target all_tests
  - ctest --no-compress-output -T Test
  - cmake --build . --target all
