language: c

jobs:
  include:
    - stage: build all
      os: linux
      compiler: gcc

    - #stage: MacOS build
      os: osx
      osx_image: xcode11.2
      compiler: gcc

    - #stage: Win64 build
      os: windows
      compiler: gcc

before_script:
  - env
  - mkdir build
  - cd build
  - cmake ..

script: cmake --build .
