name: Publish Release

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: make build dir
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: configure cmake
        run: cmake -S ${{ github.workspace }} -B ${{runner.workspace}}/build
      - name: build
        run: cmake --build ${{runner.workspace}}/build
      - name: make artifacts
        run: cmake --build ${{runner.workspace}}/build --target ziti-prox-c
      - name: zip artifacts
        if: runner.os != 'Windows'
        run: 7z a -tzip ziti-prox-c-${{ runner.os }}.zip ${{runner.workspace}}/build/programs/ziti-prox-c/ziti-prox-c
      - name: zip artifacts (WIN)
        if: runner.os == 'Windows'
        run: 7z a -tzip ziti-prox-c-${{ runner.os }}.zip ${{runner.workspace}}/build/programs/ziti-prox-c/Debug/ziti-prox-c.exe
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload release bundle
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ziti-prox-c-${{ runner.os }}.zip
          asset_name: ziti-prox-c-${{ runner.os }}.zip
          asset_content_type: application/octet-stream
