name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
          - macOS-10.15
        opts: [""]

        include:
          - os: windows-latest
            opts: -G "CodeBlocks - MinGW Makefiles"
            upload: "false"

          - os: windows-latest
            opts: ""

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo "BUILD_NUMBER = ${BUILD_NUMBER}"
          cmake -E make_directory ${{runner.workspace}}/build
      - name: cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: sdk-dependencies
        with:
          path: ${{runner.workspace}}/build/_deps
          key: ${{ runner.os }}-${{matrix.opts}}-build-${{ env.cache-name }}-${{ hashFiles('deps/*') }}

      - name: setup/build CMake
        run: |
          cmake ${{ matrix.opts }} -S ${{ github.workspace }} -B ${{runner.workspace}}/build
          cmake --build ${{runner.workspace}}/build
      - name: test
        working-directory: ${{runner.workspace}}/build
        run: ctest -VV --no-compress-output
      - name: make artifacts
        run: cmake --build ${{runner.workspace}}/build --target ziti-prox-c
      - name: zip artifacts
        if: runner.os != 'Windows'
        run: 7z a -tzip ziti-prox-c-${{ runner.os }}.zip ${{runner.workspace}}/build/programs/ziti-prox-c/ziti-prox-c
      - name: zip artifacts (WIN)
        if: runner.os == 'Windows' && matrix.upload != 'false'
        run: 7z a -tzip ziti-prox-c-${{ runner.os }}.zip ${{runner.workspace}}/build/programs/ziti-prox-c/Debug/ziti-prox-c.exe
      - name: upload artifacts
        if: matrix.upload != 'false'
        uses: actions/upload-artifact@v2
        with:
          name: ziti-prox-c-${{ runner.os }}
          path: ziti-prox-c-${{ runner.os }}.zip
