name: C/C++ CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.spec.name }}
    runs-on: ${{ matrix.spec.runner }}
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    strategy:
      fail-fast: false
      matrix:
        spec:
          - { name: 'Linux x86_64', runner: 'ubuntu-20.04', preset: 'ci-linux' }
          - { name: 'Linux ARM', runner: 'ubuntu-20.04', preset: 'ci-linux-arm', no_tests: 'true' }
          - { name: 'Linux ARM64', runner: 'ubuntu-20.04', preset: 'ci-linux-arm64', no_tests: 'true' }
          - { name: 'MacOS x86_64', runner: 'macOS-11', preset: 'ci-macOS' }
          - { name: 'MacOS arm64', runner: 'macOS-11', preset: 'ci-macOS-arm64', no_tests: 'true' }
          - { name: 'Windows x86_64', runner: 'windows-2022', preset: 'ci-windows' }
          - { name: 'Windows ARM64', runner: 'windows-2022', preset: 'ci-windows-arm64', no_tests: 'true' }
    steps:
      - name: Install Crossbuild tools
        if: startsWith(matrix.spec.runner, 'ubuntu')
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: crossbuild-essential-armhf crossbuild-essential-arm64
          version: 1.0

      - name: Add msbuild to PATH
        if: matrix.spec.runner == 'windows-2019'
        uses: microsoft/setup-msbuild@v1.1

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: '19af97cba8ca48474e4ad15a24ed50271a9ecdac'

      - uses: lukka/run-cmake@v10
        name: Configure CMake
        with:
          configurePreset: ${{ matrix.spec.preset }}
          configurePresetAdditionalArgs: "[ `-B`, `./build` ]"

      - name: build CMake
        run: cmake --build ./build

      - name: test
        if: matrix.spec.no_tests != 'true'
        working-directory: ./build
        run: ctest -VV --no-compress-output -R quick_tests

      - name: integration tests
        env:
          TEST_ID: ${{ secrets.ZITI_TEST_IDENTITY }}
          ZITI_TEST_IDENTITY: ${{ runner.workspace }}/test_id.json
          ZITI_LOG: 4
        if: matrix.spec.no_tests != 'true' && env.TEST_ID != ''
        working-directory: ./build
        shell: bash
        run: |
          echo "${TEST_ID}" > "${ZITI_TEST_IDENTITY}"
          ctest -VV --no-compress-output -R zitilib_tests

      - name: make artifacts
        run: cmake --build ./build --target ziti-prox-c --target package

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        env:
          EXE_SUFFIX: ${{ runner.os == 'Windows' && '.exe' || '' }}
          BUILD_DIR: ${{ runner.os == 'Windows' && format('{0}/', matrix.spec.build_type && matrix.spec.build_type || 'Debug') || '' }}
        with:
          name: ziti-prox-c-${{ matrix.spec.toolchain || runner.os }}
          path: ./build/programs/ziti-prox-c/**/ziti-prox-c*
      - name: upload SDK artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ziti-sdk-${{ matrix.spec.toolchain || runner.os }}
          path: ./build/package/ziti-sdk-*
